extends RefCounted
const Service = preload("res://application/character/character_creation_service.gd")
const Rules = preload("res://domain/character/creation_rules.gd")
const VIEW = preload("res://presentation/character/creation_view.tscn")
var _check: Callable

func run(check: Callable, tree: SceneTree) -> void:
	_check = check
	var service := Service.new()
	var view: Dictionary = service.read_creation()
	_verify(view.remaining.attributes == 60 and view.remaining.skills == 6, "creation starts with declared budgets")
	view.attributes.strength = 999
	_verify(service.read_creation().attributes.strength == 50, "creation view is isolated")
	var failed := service.set_value("strength", 81, 0)
	_verify(failed.code == "ATTRIBUTE_ABOVE_CAP" and service.read_creation().revision == 0, "above cap rolls back")
	failed = service.set_value("strength", 29, 0)
	_verify(failed.code == "ATTRIBUTE_BELOW_FLOOR" and service.read_creation().revision == 0, "below floor rolls back")
	failed = service.set_value("unknown", 50, 0)
	_verify(failed.code == "UNKNOWN_FIELD", "unknown number rejected")
	failed = service.confirm(0)
	_verify(failed.code == "REQUIRED_FIELD", "identity required before confirmation")
	service.set_text("name", "林", 0)
	service.set_text("role", "记者", 1)
	service.set_text("background", "雨夜归途", 2)
	_verify(service.read_creation().background == "雨夜归途", "background text saved")
	failed = service.confirm(3)
	_verify(failed.code == "UNSPENT_POINTS", "unspent points block confirmation")
	service.set_value("strength", 80, 3)
	service.set_value("dexterity", 80, 4)
	view = service.read_creation()
	_verify(view.remaining.attributes == 0, "attribute budget exactly spent")
	failed = service.allocate("charisma", 1, view.revision)
	_verify(failed.code == "POINT_BUDGET_EXCEEDED" and service.read_creation() == view, "overspend leaves snapshot unchanged")
	service.set_value("awareness", 3, 5)
	service.set_value("insight", 3, 6)
	failed = service.allocate("negotiation", 1, 7)
	_verify(failed.code == "SKILL_POINTS_EXCEEDED", "skill overspend rejected")
	view = service.read_creation()
	_verify(view.remaining.skills == 0, "skill budget exactly spent")
	failed = service.set_value("awareness", 4, 7)
	_verify(failed.code == "INVALID_VALUE" and service.read_creation() == view, "skill cap rejects without revision")
	failed = service.allocate("awareness", -1, 6)
	_verify(failed.code == "STALE_STATE", "stale creation request rejected")
	var confirmed := service.confirm(7)
	_verify(confirmed.ok and confirmed.value.locked and confirmed.value.revision == 8, "confirmation locks atomically")
	_verify(service.allocate("strength", -1, 8).code == "ALREADY_CONFIRMED", "confirmed attributes stay locked")
	_verify(service.confirm(8).code == "ALREADY_CONFIRMED", "repeat confirmation rejected")
	_verify(service.read_creation().attributes.strength == 80, "confirmed snapshot preserved")
	var reset_service := Service.new()
	reset_service.set_value("strength", 70, 0)
	reset_service.reset(1)
	_verify(reset_service.read_creation().attributes.strength == Rules.ATTRIBUTE_BASE, "reset restores starting values")
	var page: Control = VIEW.instantiate()
	tree.root.add_child(page)
	page.configure(reset_service)
	_verify(page._budget.text == page.tr("creation.budget") % [60, 6], "creation page reflects service budget")
	page._rows.strength.requested.emit("strength", 80)
	_verify(reset_service.read_creation().attributes.strength == 80, "creation control edits through service")
	page._rows.strength.requested.emit("strength", 81)
	_verify(page._rows.strength._entry.text == "80", "invalid direct value reverts in visible control")
	page.queue_free()

func _verify(value: bool, description: String) -> void:
	_check.call(value, description)
